before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: mjj7aP8uG9M3ToZEvnEZ3Rw+/1E5hycxT6WQwG6wP4OZAm0+YZBsbbodCLLc8Qn0JaHQ7yJwiJ5pweT4j2OfhAUMOYqv7RyI8NDzMD5vsmme+lqDzRjcHKhzSgPA3N+lHWnAaT5rcnFfBKUsw29Pt1dxbC1LDGcn7MJquoplfnN3wyZ1cH4lFa9Bt0D6gMclUzoUyWshdk8W2kHYFpKPMzyuJ4K1JhVfsnp01fjk2aduZwM5BMLvONWjhy09VRFF4bLBIzmp1+9vTq1ybg7K6wOQAr8FWQrLBObe42zwXlJxXyqMjUMu3DpSKiH3jdZO1wMCpaG2qnXKU357tp9uS0jvLTa8LAR8QL4rD0knfl/9tJ5DOOI0GcNhQbrEh8ve9y8npXZWH/+AGQCuXLseZTknJJQ+uT0O7uHVJOHd3pXtox01UAFOm/HEFqV/wzjHev7qbqTTCais5njKF3gIZTVZumnV6WtwFVclBCroR1h+0laRsysHh0pwDMzCUG8dtvT3n0TmjbHu2B2AN4BLCNkBZ7N6wRZFWLC9ohGn3uy6j6KgQRJoh2yXHmbLXf+JVFfBjGFgIhSSXsdF18RaAQ9wxt7vhJtWnp3e7d8tHyGRoRxCYSQ6E05C/ajQFt3OHLIzLB3Sy/3fqJeJbpSLGBL4blF2OkR8NkS85fv67z0= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
